FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y build-essential libpq-dev postgresql-client && \
    rm -rf /var/lib/apt/lists/*

RUN pip install flask psycopg2-binary folium plotly pandas

WORKDIR /app
COPY app.py /app/app.py

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
